# What runs INSIDE the local cluster, as code: namespaces, configuration,
# KEDA, the dependencies and the observability stack (docs/runbook/iac.md).
#
# Deliberately NOT here:
# - The cluster itself. k3d creates it from deploy/k3d/cluster.yaml; that part
#   is platform-specific and becomes a cloud cluster module elsewhere. The
#   k3d Terraform provider (0.0.7) is too young to build on.
# - Secrets. State files hold values in plain text, so secrets stay out of
#   state: deploy/k3d/secrets.sh creates them from .env.
# - Run-to-completion Jobs (migrations, topics) and the application chart,
#   which follow the release, not the infrastructure (deploy/k3d/*.sh).
#
# The Kubernetes YAML in deploy/k8s stays the single source: it is decoded
# here, not rewritten in HCL.

locals {
  repo = abspath("${path.module}/../../..")

  manifest_files = [
    "deploy/k8s/infra/postgres.yaml",
    "deploy/k8s/infra/kafka.yaml",
    "deploy/k8s/infra/support.yaml",
    "deploy/k8s/observability/stack.yaml",
  ]

  # kind/namespace/name is unique; the same Service name exists in two
  # namespaces (otel-collector).
  manifests = merge([
    for f in local.manifest_files : {
      for m in provider::kubernetes::manifest_decode_multi(file("${local.repo}/${f}")) :
      "${m.kind}/${try(m.metadata.namespace, "_cluster")}/${m.metadata.name}" => m
    }
  ]...)
}

resource "kubernetes_namespace_v1" "this" {
  for_each = toset(["selaras", "observability"])

  metadata {
    name = each.key
  }
}

# Schema isolation for Postgres comes from the same script compose runs.
resource "kubernetes_config_map_v1" "postgres_initdb" {
  metadata {
    name      = "postgres-initdb"
    namespace = kubernetes_namespace_v1.this["selaras"].metadata[0].name
  }
  data = {
    "01-schemas.sh" = file("${local.repo}/deploy/compose/initdb/01-schemas.sh")
  }
}

# The same rule files as compose; slo-rules.yml is generated by Sloth.
resource "kubernetes_config_map_v1" "prometheus_rules" {
  metadata {
    name      = "prometheus-rules"
    namespace = kubernetes_namespace_v1.this["observability"].metadata[0].name
  }
  data = {
    "alerts.yml"    = file("${local.repo}/deploy/compose/observability/alerts.yml")
    "slo-rules.yml" = file("${local.repo}/deploy/compose/observability/slo-rules.yml")
  }
}

resource "kubernetes_config_map_v1" "grafana_dashboards" {
  metadata {
    name      = "grafana-dashboards"
    namespace = kubernetes_namespace_v1.this["observability"].metadata[0].name
  }
  data = {
    for f in fileset("${local.repo}/deploy/grafana/dashboards", "*.json") :
    f => file("${local.repo}/deploy/grafana/dashboards/${f}")
  }
}

# KEDA from its chart, pinned to the version that was applied as a release
# manifest before (2.20.2); chart and app versions are the same.
resource "helm_release" "keda" {
  name             = "keda"
  repository       = "https://kedacore.github.io/charts"
  chart            = "keda"
  version          = "2.20.2"
  namespace        = "keda"
  create_namespace = true
}

resource "kubernetes_manifest" "this" {
  for_each = local.manifests
  manifest = each.value

  # OpenTofu is the owner of these objects. A hand edit (kubectl scale,
  # kubectl patch) takes over the edited fields as another field manager,
  # and a plain apply then refuses to put them back; forcing reclaims them,
  # so the next apply undoes the drift instead of failing on it. This is
  # only right because nothing else owns fields here: the HPAs and KEDA
  # ScaledObjects target the application units (deploy/helm), never these.
  field_manager {
    name            = "opentofu"
    force_conflicts = true
  }

  depends_on = [kubernetes_namespace_v1.this]
}
